CRITICAL - 2023-03-03 00:49:45 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 00:49:51 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 00:49:53 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 00:55:01 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 00:55:52 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 00:58:00 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 00:58:11 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 01:00:26 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 01:00:39 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 01:01:14 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 01:02:35 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 01:03:16 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-03-03 01:06:07 --> mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in APPPATH\Views\templates\header.php on line 132.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::__construct(): (HY000/2002): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', 'APPPATH\\Views\\templates\\header.php', 132)
 2 APPPATH\Views\templates\header.php(132): mysqli->__construct('192.168.150.213', 'webprogmi211', 'j@zzyAngle30', 'webprogmi211')
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\templates\\header.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1177): CodeIgniter\View\View->render('templates/header', [], true)
 6 APPPATH\Controllers\News.php(61): view('templates/header', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-03 01:10:55 --> mysqli_sql_exception: Table 'webprogmi211.eplascano_news' doesn't exist in C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\lab3\ci4\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\lab3\ci4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\lab3\ci4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\wamp64\www\lab3\ci4\app\Models\NewsModel.php(16): CodeIgniter\BaseModel->findAll()
#7 C:\wamp64\www\lab3\ci4\app\Controllers\News.php(15): App\Models\NewsModel->getNews()
#8 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(934): App\Controllers\News->index()
#9 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
#10 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\lab3\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-03 01:10:55 --> Table 'webprogmi211.eplascano_news' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `eplascano_news`', [], false)
 2 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\NewsModel.php(16): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\News.php(15): App\Models\NewsModel->getNews()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-03 01:11:07 --> mysqli_sql_exception: Table 'webprogmi211.eplascano_news' doesn't exist in C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `ep...', 0)
#1 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ep...')
#2 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ep...')
#3 C:\wamp64\www\lab3\ci4\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ep...', Array, false)
#4 C:\wamp64\www\lab3\ci4\system\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\lab3\ci4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\lab3\ci4\system\Model.php(729): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\wamp64\www\lab3\ci4\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\wamp64\www\lab3\ci4\app\Controllers\News.php(71): CodeIgniter\BaseModel->save(Array)
#9 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(934): App\Controllers\News->create()
#10 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
#11 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\wamp64\www\lab3\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-03-03 01:11:07 --> Table 'webprogmi211.eplascano_news' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `eplascano_news` (`title`, `slug`, `body`) VALUES (:title:, :slug:, :body:)', [...], false)
 2 SYSTEMPATH\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(729): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\News.php(71): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-03 01:13:48 --> mysqli_sql_exception: Table 'webprogmi211.eplascano_news' doesn't exist in C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php(295): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\wamp64\www\lab3\ci4\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\wamp64\www\lab3\ci4\system\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
#5 C:\wamp64\www\lab3\ci4\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\wamp64\www\lab3\ci4\app\Models\NewsModel.php(16): CodeIgniter\BaseModel->findAll()
#7 C:\wamp64\www\lab3\ci4\app\Controllers\News.php(15): App\Models\NewsModel->getNews()
#8 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(934): App\Controllers\News->index()
#9 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
#10 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\wamp64\www\lab3\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-03-03 01:13:48 --> Table 'webprogmi211.eplascano_news' doesn't exist
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `eplascano_news`', [], false)
 2 SYSTEMPATH\Model.php(240): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Models\NewsModel.php(16): CodeIgniter\BaseModel->findAll()
 5 APPPATH\Controllers\News.php(15): App\Models\NewsModel->getNews()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-03 01:15:43 --> mysqli_sql_exception: Duplicate entry 'turbo' for key 'news.slug' in C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\wamp64\www\lab3\ci4\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `ne...', 0)
#1 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ne...')
#2 C:\wamp64\www\lab3\ci4\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ne...')
#3 C:\wamp64\www\lab3\ci4\system\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ne...', Array, false)
#4 C:\wamp64\www\lab3\ci4\system\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\wamp64\www\lab3\ci4\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\wamp64\www\lab3\ci4\system\Model.php(729): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\wamp64\www\lab3\ci4\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\wamp64\www\lab3\ci4\app\Controllers\News.php(71): CodeIgniter\BaseModel->save(Array)
#9 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(934): App\Controllers\News->create()
#10 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
#11 C:\wamp64\www\lab3\ci4\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\wamp64\www\lab3\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-03-03 01:15:43 --> Duplicate entry 'turbo' for key 'news.slug'
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2295): CodeIgniter\Database\BaseConnection->query('INSERT INTO `news` (`title`, `slug`, `body`) VALUES (:title:, :slug:, :body:)', [...], false)
 2 SYSTEMPATH\Model.php(329): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(729): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\News.php(71): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\News->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\News))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
